apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged
  namespace: insecure-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged
  template:
    metadata:
      labels:
        app: privileged
    spec:
      hostPID: true # vector: nsenter works now for namespaces running outside the container
      hostNetwork: true # vector: sniff traffic with tcpdump, try to bypass NetworkPolicies
      hostIPC: true # vector: look for shared resources in /dev/shm and ipcs
      nodeName: k8s-control-plane-node # deploy workload on a control plane Node
      containers:
        - name: sidecar-container
          image: malicious-sidecar
          command: ["/bin/sleep", "3650d"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host-root
      volumes:
        - name: host-root # vector: mount the host filesystem
          hostPath:
            path: /
